/**
 * src/constants/ActionTypes.js
 */

export const LOAD_COURSES_SUCCESS  = 'LOAD_COURSES_SUCCESS';
export const SAVE_COURSE_SUCCESS   = 'SAVE_COURSES_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSES_SUCCESS';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
